### ISSUE TITLE
support FreeBSD 13.0-CURRENT.

### ISSUE THREAD

**Issue by lrosenman** [lsof-org/lsof-linux#30]
FreeBSD just up'd the version on HEAD from 12 to 13, and re-opened the tree. 

We just need to tell Configure that it's ok.

For now, it's the same [AK]BI as 12.

**Comment by masatake** [comment]
I already removed directories of all dialects other than Linux. There is no FreeBSD related code here.
This repository is for queuing Linux related changes.
